### PR TITLE
WIP#287 Upgrade CE&Scala v3.0. Switch to munit

### PR DESCRIPTION
**Pull request by landerlo**
Version bumps to Cats-effect 3.0 and Scala 3.0.

Adapted the Timer to CE3 and fixed dotty related compilation failures.

Mechanically switched to Munit, though haven't done much about the lack of depth in the categorisation.
So the behaviours are repeated in the test description which is not entirely satisfactory but you some other approach could be done with tags or subclasses, though I have never tried those with munit.

I've left 2.12 as it cross compiles with 2.13 and 3.0.
It compiles and tests are green for the 3 versions.

Pending are the mdocs examples. If you're happy with the changes I can migrate the examples to CE3.

### CODE REVIEW

**Comment by landerlo** [comment]
Had some time to look at the new CE3.0 typeclasses and I've migrated the mdoc code examples to CE3.0.
There's no progress in CE3.0 Monix so I had to replace Task with IO.

Other than that, the non automatic migration is in the mtl example requiring  `Service[F: Timer : Sync]`.
The migration is `Timer -> Temporal`, but `Temporal` is a `Monad` part of the hierarchy, so it feels like in order to have effect suspension and timer effects you need `Async` which in the new TC hierarchy inherits from both `Sync` and `Temporal`.

**Comment by cb372** [comment]
Thank you for all the effort you've put into this, especially migrating to MUnit. It's looking great so far.

Switching the docs from Task to IO is fine with me.

Just a word of warning: I think it makes sense to merge #284 before this PR, so there will be some merge conflicts to handle.

**Comment by gvolpe** [comment]
@cb372 I had copied some code from this library to get this application working, hope that's okay with you? I plan to delete it as soon as there is a release for CE3. https://github.com/gvolpe/pfps-shopping-cart/pull/324

**Comment by balthz** [comment]
First of all, thanks for a great library! I'm in the same boat as @gvolpe and will switch back to this library once a release for CE3 is out.

**Comment by cb372** [comment]
@landerlo Sorry, there are those merge conflicts I promised you 😄 

@gvolpe @balthz Of course, no problem.

**Comment by cb372** [comment]
@landerlo I see you had to downgrade to 3.0.0-RC1. It looks like cats-core 2.5.0 is available for 3.0.0-RC2, so upgrading cats-core should fix that?

**Comment by weihsiu** [comment]
when can we expect this pr to get merged?

**Comment by TimWSpence** [comment]
Thanks you all for your hard work on this! ❤️ Is there anything I can do to help get this over the line?

**Comment by gvolpe** [comment]
I guess this can now be closed @cb372 ?

**Pull request closed without merging**
