### PR TITLE
Add meet

### PR DESCRIPTION
**Pull request by LukaJCB**
Also adds `join` as a method on `RetryPolicy` for some cute symmetry :)

### CODE REVIEW

**Comment by cb372** [comment]
Great stuff! A couple of comments:

1. Shall we deprecate/remove the `capDelay` function, as the same thing can now be achieved more elegantly by composing policies using `meet`, as in your example in https://github.com/cb372/cats-retry/issues/38#issuecomment-504181123 ?

2. Could you update the documentation (https://github.com/cb372/cats-retry/blob/master/modules/docs/src/main/tut/docs/policies.md#composing-policies) please

**Comment by LukaJCB** [comment]
Sounds good to me, I'll update the docs on the other PR as well :)

**Comment by LukaJCB** [comment]
Instead of deprecating, we could also simply implement it in terms of `meet` and then use it as an example for the docs?

**Comment by cb372** [comment]
Good idea, let’s do that

**Comment by LukaJCB** [comment]
I'm also gonna change up the `join` example since it caps the delay at 1 second, but an exponential backoff retrying only 5 times is never going to actually reach one second :smile:

**Pull request merged**
