### PR TITLE
Add logo to microsite and Readme

### PR DESCRIPTION
**Pull request by LukaJCB**
Many thanks to @zelenya for providing the logo ❤️

### CODE REVIEW

**Comment by cb372** [comment]
Hey @LukaJCB, thanks for this. But the files need slightly different names and format because we are using the sbt-microsites `light` theme (which was introduced as the default theme in v1.0). See the docs here: https://47deg.github.io/sbt-microsites/docs/customize/

It looks like we need to get the logo as an svg. Would that be possible?

In the short term we could revert to the `pattern` theme? But I think `light` looks nicer so I'd like to use that in the long term.

**Comment by cb372** [comment]
I've updated the PR to use an SVG logo so it works with the sbt-microsites 'light' pattern. 

It looks fine in Firefox:

Screenshot 2020-01-07 at 19 44 48

but really weird in Chrome:

Screenshot 2020-01-07 at 19 44 39

If I open just the SVG file in a Chrome tab, it renders fine.

Not sure what to do about this. I'll see if any of the 47deg design boffins can help.

**Comment by Zelenya** [comment]
Maybe the svg itself is the issues. Maybe my Photoshop is misbehaving

**Comment by calvellido** [comment]
Hi!  This PR updates SVGs into this branch:

https://github.com/cb372/cats-retry/pull/152

**Comment by cb372** [comment]
Thank you @calvellido! I've tested locally and it looks fine now.

**Pull request merged**
