### PR TITLE
Add support for Scala 3

### PR DESCRIPTION
**Pull request by aeons**
This PR adds support for Scala 3, by switching the test framework to munit. Docs are not updated yet.

I just saw #291 doing this, but switching to CE3 as well.

I think there is value in having both a CE2 and CE3 version, both published for Scala 3.

I don't know how this should be handled or merged. I know [munit-cats-effect](https://github.com/typelevel/munit-cats-effect) publishes under two different artifacts for the different cats-effect versions.

### CODE REVIEW

**Comment by aeons** [comment]
Maybe having one last release on CE2/Scala 3 before switching to CE3?

**Comment by cb372** [comment]
Hey, thanks for this! Yes, let's have one last 2.x release that cross-publishes for Scala 2 and 3 but is still built against CE 2. I'm sure that will help a few people with migration.

FYI I've switched this PR to the `series/2.x` branch.

I haven't reviewed yet. I'll wait until you update the examples in the docs.

**Comment by aeons** [comment]
Everything should work now.

**Review by cb372 — APPROVED** [review]
LGTM. Thanks for this!

**Comment by cb372** [comment]
I made a follow-up PR to bump the Scala version to RC3 and then released this as v2.1.1. We can make another release once Scala 3 is released.

**Pull request merged**
