### PR TITLE
Use scheduler for Sleep[Future] instead of blocking

### PR DESCRIPTION
**Pull request by Billzabob**

### CODE REVIEW

**Comment by LukaJCB** [comment]
Hmm it seems like the `mdoc` task in running forever

**Comment by cb372** [comment]
`mdoc` was hanging because the single-thread executor is not using a daemon thread. The process can't shutdown until all non-daemon threads have finished, so it was stuck running forever.

I've just pushed a commit to fix this.

**Comment by cb372** [comment]
Not sure what's up with GitHub, but my commit to your branch isn't showing up in the PR. It's here: https://github.com/Billzabob/cats-retry/commit/4ccb58295743bdf9a0c6f43b2cb0a0054024f032

@Billzabob Sorry, do you mind opening a new PR that includes that change?

**Comment by cb372** [comment]
Actually don't worry about it, I made a new PR

**Pull request closed without merging**
