### PR TITLE
Add retryingMM with argument wasSuccessful: A => M[Boolean]

### PR DESCRIPTION
**Pull request by d10xa**

### CODE REVIEW

**Comment by cb372** [comment]
Looks good! I'm not sure about the name `retryingMM`, but I can't think of a better one 🤷‍♂️ 

Do you mind adding some documentation to https://github.com/cb372/cats-retry/blob/master/modules/docs/src/main/mdoc/docs/combinators.md ?

**Comment by d10xa** [comment]
`retryingMM` is not a good name. When creating a request, I was hoping that you would come up with a name.
retryingOnSomeErrors has the same argument `isWorthRetrying: E => Boolean`.  I can leave name `retryingMM` as it is, but in that way `retryingOnSomeErrorsM` will be very confused.

**Comment by cb372** [comment]
@lukajcb any ideas about the naming?

**Comment by cb372** [comment]
It’s worth pointing out that I don’t even think `retryingM` is a very good name. I copied it from the Haskell retry package in the early days of cats-retry and never got around to renaming it.

**Comment by d10xa** [comment]
An another change I would like to see is additional parameter `onGiveUp: A => M[A]` (at RetryingPartiallyApplied.apply and RetryingOnSomeErrorsPartiallyApplied.apply)
I suggest to add function `retrying` without `M` as generic implementation of the following:

```
M.tailRecM(RetryStatus.NoRetriesYet) { status =>
    action.flatMap { a =>
      wasSuccessful(a).ifM(
        M.pure(Right(a)), // stop the recursion
        for {
          nextStep <- applyPolicy(policy, status)
          _        <- onFailure(a, buildRetryDetails(status, nextStep))
          result <- nextStep match {
            case NextStep.RetryAfterDelay(delay, updatedStatus) =>
              S.sleep(delay) *>
                M.pure(Left(updatedStatus)) // continue recursion
            case NextStep.GiveUp =>
              onGiveUp(a).map(Right(_))
          }
        } yield result
      )
    }
  }
```

But I do not know how to make it generic, since RetryingPartiallyApplied need Monad, and RetryingOnSomeErrorsPartiallyApplied - MonadError.
@cb372 what do you think?

**Comment by cb372** [comment]
Closing as superseded by #283

**Pull request closed without merging**
